### ISSUE TITLE
Crash when node have no defined sound

### ISSUE THREAD

**Issue by oz-tal** [gamefreq0/extended_placement#14]
This line cause a crash when `placed_node_def.sounds` is nil: https://github.com/gamefreq0/extended_placement/blob/master/init.lua#L166

**Comment by gamefreq0** [comment]
Feel free to give it a try now, it should be fixed. I'm a bit busy right now and can't test myself. Fix should now be in the latest CDB release. No new crashes from the fix, so at worst I didn't break anything already working.

**Comment by oz-tal** [comment]
Hi, thanks for looking into it. I haven't had time to do some testing yet, but I believe you have to check if `placed_node_def.sounds` is nil before chaining `.place` to it.

**Comment by gamefreq0** [comment]
Ah, good catch. Should be fixed now.

**Comment by gamefreq0** [comment]
Given that I've not heard anything further, I'm closing this under the assumption that my changes have fixed the original issue.
