### ISSUE TITLE
Places two nodes if the player can reach a node and has their highlight on it

### ISSUE THREAD

**Issue by Montandalar** [gamefreq0/extended_placement#6]
In the case of bridge building it is often the case that there is nothing but air for a good distance and so the extended placement works as expected. However, when looking at the edge of terrain it is common to be able to reach the ground with your hand. 

To reproduce
1. Fire up an ordinary Minetest Game survival world in creative mode (which has a large reach)
2. Look at the edge of some of the ground terrain, but close to the edge so that the node highlight is on the ground on the lower level.
3. Place a node with the extended functionality
4. Note how the node above the player's highlight node is placed *as well as* the extended node.

This is probably solvable by checking with a raycast if the player can reach and place a node that is further away than the extended placement position, and either disabling extended placement or maybe temporarily reducing their reach (I'm not sure if that's possible without some dirty hacks though, since overriding the global hand item doesn't work for multiplayer).

**Comment by gamefreq0** [comment]
Fixed as of merging PR #9. Will bump the release on CDB in a few minutes.
